import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { QueryClientProvider, queryClient } from '../src/shared/lib/config/react-query'
import { Header } from '@/src/widgets/Header'
import { Footer } from '@/src/widgets/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
    const {
        children,
    } = props

    return (
        <html lang="en">
            <body className={inter.className}>
                <QueryClientProvider client={queryClient}>
                    <AntdRegistry>
                        <Header />
                        {children}
                        <Footer />
                    </AntdRegistry>
                </QueryClientProvider>
            </body>
        </html>
    )
}
